import { describe, expect, it } from "vitest";
import type { NovelDocument } from "@zed-novel-reader/core";
import { formatNovel } from "../src/index.js";

const document: NovelDocument = {
  metadata: { title: "示例书名", formatVersion: 1 },
  source: { encoding: "utf-8", autoSegmented: false },
  chapters: [
    {
      id: "chapter_0001",
      title: "第一章 初见",
      paragraphs: ["第一行\n第二行", "包含 */ 终止符\n@danger\n*danger"],
      autoGenerated: false,
    },
  ],
};

describe("formatNovel", () => {
  it("formats plain text without comment decoration", () => {
    expect(formatNovel(document, "plain")).toBe(
      "示例书名\n\n第一章 初见\n\n第一行\n第二行\n\n包含 */ 终止符\n@danger\n*danger\n",
    );
  });

  it("formats metadata, chapter title, paragraphs and chapter id as grammar-compatible JSDoc", () => {
    expect(formatNovel(document, "jsdoc")).toBe(`/**
 * @novel-title 示例书名
 * @format-version 1
 */

/**
 * 第一章 初见
 *
 * 第一行
 * 第二行
 *
 * 包含 *\\/ 终止符
 * \\@danger
 * \\*danger
 *
 * @chapter-id chapter_0001
 */
`);
  });

  it("uses jsdoc by default", () => {
    expect(formatNovel(document)).toBe(formatNovel(document, "jsdoc"));
  });

  it("escapes every body block terminator so only formatter-owned terminators remain", () => {
    const output = formatNovel(document);
    expect(output.match(/\*\//gu)).toHaveLength(2);
    expect(output).toContain("*\\/");
  });
});
