import { describe, expect, it } from "vitest";
import { parseNovelText } from "../src/index.js";

describe("parseNovelText", () => {
  it("recognizes a whole-line Chinese chapter heading", () => {
    const document = parseNovelText("第一章 初见\n第一段。", "书名", "utf-8");

    expect(document.chapters).toEqual([
      {
        id: "chapter_0001",
        title: "第一章 初见",
        paragraphs: ["第一段。"],
        autoGenerated: false,
      },
    ]);
  });

  it.each([
    "第 12 节  风起",
    "第十二卷：归来",
    "第３回 夜话",
    "第两百部 终局",
    "第一篇 序曲",
  ])("recognizes Chinese heading variant: %s", (heading) => {
    expect(parseNovelText(`${heading}\n正文`, "书", "utf-8").chapters[0]?.title).toBe(heading);
  });

  it.each(["Chapter 12 The Return", "CHAPTER IV: Home", "Prologue", "Epilogue - Afterwards"])(
    "recognizes English heading: %s",
    (heading) => {
      expect(parseNovelText(`${heading}\nBody`, "Book", "utf-8").chapters[0]?.title).toBe(heading);
    },
  );

  it("does not match chapter-like text embedded in prose", () => {
    const document = parseNovelText(
      "第一章 真标题\r\n他说第十二章很精彩，但这只是正文。\r下一行\n\n第二段",
      "书",
      "utf-8",
    );
    expect(document.chapters).toHaveLength(1);
    expect(document.chapters[0]?.paragraphs).toEqual([
      "他说第十二章很精彩，但这只是正文。\n下一行",
      "第二段",
    ]);
  });

  it("creates explicitly marked automatic segments when headings are absent", () => {
    const document = parseNovelText("无标题正文。\n\n第二段。", "书", "utf-8");
    expect(document.source.autoSegmented).toBe(true);
    expect(document.chapters).toEqual([
      {
        id: "auto_0001",
        title: "[自动分段 1]",
        paragraphs: ["无标题正文。", "第二段。"],
        autoGenerated: true,
      },
    ]);
  });

  it("preserves preface text before the first explicit chapter", () => {
    const document = parseNovelText("这是前言。\n\n第一章 开始\n正文。", "书", "utf-8");

    expect(document.source.autoSegmented).toBe(true);
    expect(document.chapters).toEqual([
      {
        id: "auto_0001",
        title: "[自动分段 1]",
        paragraphs: ["这是前言。"],
        autoGenerated: true,
      },
      {
        id: "chapter_0001",
        title: "第一章 开始",
        paragraphs: ["正文。"],
        autoGenerated: false,
      },
    ]);
  });

  it("keeps an empty document empty", () => {
    expect(parseNovelText(" \r\n\t", "空", "utf-8").chapters).toEqual([]);
  });
});
