/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SLASH_STAR_STAR = 1,
  aux_sym_metadata_entry_token1 = 2,
  anon_sym_ATnovel_DASHtitle = 3,
  anon_sym_ATformat_DASHversion = 4,
  sym_metadata_value = 5,
  anon_sym_ATchapter_DASHid = 6,
  aux_sym_chapter_title_token1 = 7,
  sym__line_prefix = 8,
  aux_sym__blank_line_token1 = 9,
  sym__block_end = 10,
  sym_chapter_id = 11,
  anon_sym_ATbookmark = 12,
  aux_sym_bookmark_token1 = 13,
  sym_bookmark_attributes = 14,
  sym__newline = 15,
  sym_source_file = 16,
  sym_metadata_block = 17,
  sym_metadata_entry = 18,
  sym_metadata_key = 19,
  sym_chapter_block = 20,
  sym_chapter_title = 21,
  sym_paragraph = 22,
  sym_text_line = 23,
  sym__blank_line = 24,
  sym_bookmark = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_source_file_repeat2 = 27,
  aux_sym_metadata_block_repeat1 = 28,
  aux_sym_chapter_block_repeat1 = 29,
  aux_sym_paragraph_repeat1 = 30,
  aux_sym_paragraph_repeat2 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH_STAR_STAR] = "/**",
  [aux_sym_metadata_entry_token1] = "metadata_entry_token1",
  [anon_sym_ATnovel_DASHtitle] = "@novel-title",
  [anon_sym_ATformat_DASHversion] = "@format-version",
  [sym_metadata_value] = "metadata_value",
  [anon_sym_ATchapter_DASHid] = "@chapter-id",
  [aux_sym_chapter_title_token1] = "chapter_title_token1",
  [sym__line_prefix] = "_line_prefix",
  [aux_sym__blank_line_token1] = "_blank_line_token1",
  [sym__block_end] = "_block_end",
  [sym_chapter_id] = "chapter_id",
  [anon_sym_ATbookmark] = "@bookmark",
  [aux_sym_bookmark_token1] = "bookmark_token1",
  [sym_bookmark_attributes] = "bookmark_attributes",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_metadata_block] = "metadata_block",
  [sym_metadata_entry] = "metadata_entry",
  [sym_metadata_key] = "metadata_key",
  [sym_chapter_block] = "chapter_block",
  [sym_chapter_title] = "chapter_title",
  [sym_paragraph] = "paragraph",
  [sym_text_line] = "text_line",
  [sym__blank_line] = "_blank_line",
  [sym_bookmark] = "bookmark",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_metadata_block_repeat1] = "metadata_block_repeat1",
  [aux_sym_chapter_block_repeat1] = "chapter_block_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_paragraph_repeat2] = "paragraph_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH_STAR_STAR] = anon_sym_SLASH_STAR_STAR,
  [aux_sym_metadata_entry_token1] = aux_sym_metadata_entry_token1,
  [anon_sym_ATnovel_DASHtitle] = anon_sym_ATnovel_DASHtitle,
  [anon_sym_ATformat_DASHversion] = anon_sym_ATformat_DASHversion,
  [sym_metadata_value] = sym_metadata_value,
  [anon_sym_ATchapter_DASHid] = anon_sym_ATchapter_DASHid,
  [aux_sym_chapter_title_token1] = aux_sym_chapter_title_token1,
  [sym__line_prefix] = sym__line_prefix,
  [aux_sym__blank_line_token1] = aux_sym__blank_line_token1,
  [sym__block_end] = sym__block_end,
  [sym_chapter_id] = sym_chapter_id,
  [anon_sym_ATbookmark] = anon_sym_ATbookmark,
  [aux_sym_bookmark_token1] = aux_sym_bookmark_token1,
  [sym_bookmark_attributes] = sym_bookmark_attributes,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_metadata_block] = sym_metadata_block,
  [sym_metadata_entry] = sym_metadata_entry,
  [sym_metadata_key] = sym_metadata_key,
  [sym_chapter_block] = sym_chapter_block,
  [sym_chapter_title] = sym_chapter_title,
  [sym_paragraph] = sym_paragraph,
  [sym_text_line] = sym_text_line,
  [sym__blank_line] = sym__blank_line,
  [sym_bookmark] = sym_bookmark,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_metadata_block_repeat1] = aux_sym_metadata_block_repeat1,
  [aux_sym_chapter_block_repeat1] = aux_sym_chapter_block_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_paragraph_repeat2] = aux_sym_paragraph_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_metadata_entry_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_ATnovel_DASHtitle] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATformat_DASHversion] = {
    .visible = true,
    .named = false,
  },
  [sym_metadata_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATchapter_DASHid] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_chapter_title_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__line_prefix] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__blank_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__block_end] = {
    .visible = false,
    .named = true,
  },
  [sym_chapter_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATbookmark] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_bookmark_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_bookmark_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_block] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_key] = {
    .visible = true,
    .named = true,
  },
  [sym_chapter_block] = {
    .visible = true,
    .named = true,
  },
  [sym_chapter_title] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym_bookmark] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_metadata_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chapter_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attributes = 1,
  field_id = 2,
  field_key = 3,
  field_title = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attributes] = "attributes",
  [field_id] = "id",
  [field_key] = "key",
  [field_title] = "title",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_attributes, 4},
  [1] =
    {field_key, 1},
    {field_value, 3},
  [3] =
    {field_id, 9},
    {field_title, 3},
  [5] =
    {field_id, 10},
    {field_title, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(56);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '@') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(72);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(65);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(2);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(47);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(52);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(64);
      END_STATE();
    case 14:
      if (lookahead == '/') ADVANCE(70);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == 'b') ADVANCE(40);
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(62);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'k') ADVANCE(69);
      END_STATE();
    case 30:
      if (lookahead == 'k') ADVANCE(34);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 34:
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 41:
      if (lookahead == 'p') ADVANCE(48);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 51:
      if (lookahead == 'v') ADVANCE(21);
      END_STATE();
    case 52:
      if (lookahead == 'v') ADVANCE(24);
      END_STATE();
    case 53:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '*') ADVANCE(71);
      END_STATE();
    case 54:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 55:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR_STAR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_metadata_entry_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_ATnovel_DASHtitle);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_ATformat_DASHversion);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_metadata_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_ATchapter_DASHid);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_chapter_title_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__line_prefix);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym__blank_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym__blank_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__block_end);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_chapter_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_ATbookmark);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_bookmark_token1);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_bookmark_attributes);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '*') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 54},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 55},
  [53] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH_STAR_STAR] = ACTIONS(1),
    [aux_sym_metadata_entry_token1] = ACTIONS(1),
    [anon_sym_ATnovel_DASHtitle] = ACTIONS(1),
    [anon_sym_ATformat_DASHversion] = ACTIONS(1),
    [anon_sym_ATchapter_DASHid] = ACTIONS(1),
    [sym_chapter_id] = ACTIONS(1),
    [anon_sym_ATbookmark] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(41),
    [sym_metadata_block] = STATE(18),
    [sym_chapter_block] = STATE(18),
    [sym_bookmark] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH_STAR_STAR] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR_STAR,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym__newline,
    STATE(4), 1,
      aux_sym_source_file_repeat2,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    STATE(18), 3,
      sym_metadata_block,
      sym_chapter_block,
      sym_bookmark,
  [21] = 4,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR_STAR,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym_source_file_repeat2,
    STATE(18), 3,
      sym_metadata_block,
      sym_chapter_block,
      sym_bookmark,
  [36] = 4,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR_STAR,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym_source_file_repeat2,
    STATE(18), 3,
      sym_metadata_block,
      sym_chapter_block,
      sym_bookmark,
  [51] = 4,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR_STAR,
    STATE(5), 1,
      aux_sym_source_file_repeat2,
    STATE(18), 3,
      sym_metadata_block,
      sym_chapter_block,
      sym_bookmark,
  [66] = 4,
    ACTIONS(20), 1,
      sym__line_prefix,
    ACTIONS(22), 1,
      aux_sym__blank_line_token1,
    STATE(11), 2,
      sym__blank_line,
      aux_sym_paragraph_repeat2,
    STATE(14), 2,
      sym_text_line,
      aux_sym_paragraph_repeat1,
  [81] = 3,
    ACTIONS(24), 1,
      sym__line_prefix,
    STATE(6), 2,
      sym_text_line,
      aux_sym_paragraph_repeat1,
    STATE(9), 2,
      sym_paragraph,
      aux_sym_chapter_block_repeat1,
  [93] = 4,
    ACTIONS(28), 1,
      aux_sym_chapter_title_token1,
    STATE(36), 1,
      sym_metadata_key,
    STATE(37), 1,
      sym_chapter_title,
    ACTIONS(26), 2,
      anon_sym_ATnovel_DASHtitle,
      anon_sym_ATformat_DASHversion,
  [107] = 3,
    ACTIONS(30), 1,
      sym__line_prefix,
    STATE(6), 2,
      sym_text_line,
      aux_sym_paragraph_repeat1,
    STATE(10), 2,
      sym_paragraph,
      aux_sym_chapter_block_repeat1,
  [119] = 3,
    ACTIONS(32), 1,
      sym__line_prefix,
    STATE(6), 2,
      sym_text_line,
      aux_sym_paragraph_repeat1,
    STATE(10), 2,
      sym_paragraph,
      aux_sym_chapter_block_repeat1,
  [131] = 3,
    ACTIONS(22), 1,
      aux_sym__blank_line_token1,
    ACTIONS(35), 1,
      sym__line_prefix,
    STATE(17), 2,
      sym__blank_line,
      aux_sym_paragraph_repeat2,
  [142] = 3,
    ACTIONS(37), 1,
      sym__line_prefix,
    ACTIONS(40), 1,
      sym__block_end,
    STATE(12), 2,
      sym_metadata_entry,
      aux_sym_metadata_block_repeat1,
  [153] = 3,
    ACTIONS(42), 1,
      sym__line_prefix,
    ACTIONS(44), 1,
      sym__block_end,
    STATE(12), 2,
      sym_metadata_entry,
      aux_sym_metadata_block_repeat1,
  [164] = 3,
    ACTIONS(46), 1,
      sym__line_prefix,
    ACTIONS(49), 1,
      aux_sym__blank_line_token1,
    STATE(14), 2,
      sym_text_line,
      aux_sym_paragraph_repeat1,
  [175] = 3,
    ACTIONS(11), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR_STAR,
  [186] = 3,
    ACTIONS(53), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR_STAR,
  [197] = 3,
    ACTIONS(56), 1,
      sym__line_prefix,
    ACTIONS(58), 1,
      aux_sym__blank_line_token1,
    STATE(17), 2,
      sym__blank_line,
      aux_sym_paragraph_repeat2,
  [208] = 3,
    ACTIONS(63), 1,
      sym__newline,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR_STAR,
  [219] = 1,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR_STAR,
      sym__newline,
  [225] = 1,
    ACTIONS(67), 3,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR_STAR,
      sym__newline,
  [231] = 2,
    STATE(36), 1,
      sym_metadata_key,
    ACTIONS(26), 2,
      anon_sym_ATnovel_DASHtitle,
      anon_sym_ATformat_DASHversion,
  [239] = 2,
    ACTIONS(69), 1,
      sym__line_prefix,
    STATE(13), 2,
      sym_metadata_entry,
      aux_sym_metadata_block_repeat1,
  [247] = 1,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR_STAR,
      sym__newline,
  [253] = 1,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR_STAR,
      sym__newline,
  [259] = 2,
    ACTIONS(75), 1,
      aux_sym_metadata_entry_token1,
    ACTIONS(77), 1,
      sym__newline,
  [266] = 2,
    ACTIONS(79), 1,
      anon_sym_ATchapter_DASHid,
    ACTIONS(81), 1,
      aux_sym_chapter_title_token1,
  [273] = 2,
    ACTIONS(83), 1,
      sym__line_prefix,
    ACTIONS(85), 1,
      aux_sym__blank_line_token1,
  [280] = 2,
    ACTIONS(81), 1,
      aux_sym_chapter_title_token1,
    ACTIONS(87), 1,
      anon_sym_ATchapter_DASHid,
  [287] = 1,
    ACTIONS(89), 2,
      sym__line_prefix,
      sym__block_end,
  [292] = 2,
    ACTIONS(91), 1,
      sym__line_prefix,
    ACTIONS(93), 1,
      aux_sym__blank_line_token1,
  [299] = 2,
    ACTIONS(95), 1,
      aux_sym__blank_line_token1,
    STATE(7), 1,
      sym__blank_line,
  [306] = 1,
    ACTIONS(97), 1,
      sym__newline,
  [310] = 1,
    ACTIONS(99), 1,
      anon_sym_ATbookmark,
  [314] = 1,
    ACTIONS(101), 1,
      sym__newline,
  [318] = 1,
    ACTIONS(103), 1,
      sym__newline,
  [322] = 1,
    ACTIONS(105), 1,
      aux_sym_metadata_entry_token1,
  [326] = 1,
    ACTIONS(107), 1,
      sym__newline,
  [330] = 1,
    ACTIONS(109), 1,
      aux_sym_metadata_entry_token1,
  [334] = 1,
    ACTIONS(111), 1,
      sym__newline,
  [338] = 1,
    ACTIONS(113), 1,
      aux_sym_metadata_entry_token1,
  [342] = 1,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
  [346] = 1,
    ACTIONS(117), 1,
      sym_bookmark_attributes,
  [350] = 1,
    ACTIONS(119), 1,
      aux_sym_metadata_entry_token1,
  [354] = 1,
    ACTIONS(121), 1,
      sym_chapter_id,
  [358] = 1,
    ACTIONS(81), 1,
      aux_sym_chapter_title_token1,
  [362] = 1,
    ACTIONS(123), 1,
      aux_sym_metadata_entry_token1,
  [366] = 1,
    ACTIONS(125), 1,
      aux_sym_bookmark_token1,
  [370] = 1,
    ACTIONS(127), 1,
      sym__newline,
  [374] = 1,
    ACTIONS(129), 1,
      sym_chapter_id,
  [378] = 1,
    ACTIONS(131), 1,
      sym__block_end,
  [382] = 1,
    ACTIONS(133), 1,
      sym__newline,
  [386] = 1,
    ACTIONS(135), 1,
      sym_metadata_value,
  [390] = 1,
    ACTIONS(137), 1,
      sym__block_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 51,
  [SMALL_STATE(6)] = 66,
  [SMALL_STATE(7)] = 81,
  [SMALL_STATE(8)] = 93,
  [SMALL_STATE(9)] = 107,
  [SMALL_STATE(10)] = 119,
  [SMALL_STATE(11)] = 131,
  [SMALL_STATE(12)] = 142,
  [SMALL_STATE(13)] = 153,
  [SMALL_STATE(14)] = 164,
  [SMALL_STATE(15)] = 175,
  [SMALL_STATE(16)] = 186,
  [SMALL_STATE(17)] = 197,
  [SMALL_STATE(18)] = 208,
  [SMALL_STATE(19)] = 219,
  [SMALL_STATE(20)] = 225,
  [SMALL_STATE(21)] = 231,
  [SMALL_STATE(22)] = 239,
  [SMALL_STATE(23)] = 247,
  [SMALL_STATE(24)] = 253,
  [SMALL_STATE(25)] = 259,
  [SMALL_STATE(26)] = 266,
  [SMALL_STATE(27)] = 273,
  [SMALL_STATE(28)] = 280,
  [SMALL_STATE(29)] = 287,
  [SMALL_STATE(30)] = 292,
  [SMALL_STATE(31)] = 299,
  [SMALL_STATE(32)] = 306,
  [SMALL_STATE(33)] = 310,
  [SMALL_STATE(34)] = 314,
  [SMALL_STATE(35)] = 318,
  [SMALL_STATE(36)] = 322,
  [SMALL_STATE(37)] = 326,
  [SMALL_STATE(38)] = 330,
  [SMALL_STATE(39)] = 334,
  [SMALL_STATE(40)] = 338,
  [SMALL_STATE(41)] = 342,
  [SMALL_STATE(42)] = 346,
  [SMALL_STATE(43)] = 350,
  [SMALL_STATE(44)] = 354,
  [SMALL_STATE(45)] = 358,
  [SMALL_STATE(46)] = 362,
  [SMALL_STATE(47)] = 366,
  [SMALL_STATE(48)] = 370,
  [SMALL_STATE(49)] = 374,
  [SMALL_STATE(50)] = 378,
  [SMALL_STATE(51)] = 382,
  [SMALL_STATE(52)] = 386,
  [SMALL_STATE(53)] = 390,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(25),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_block_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_metadata_block_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat2, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat2, 2, 0, 0), SHIFT_REPEAT(35),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chapter_block, 13, 0, 4),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata_block, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bookmark, 6, 0, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chapter_block, 12, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__blank_line, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__blank_line, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata_entry, 5, 0, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_line, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_line, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chapter_title, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata_key, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_novel(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "novel",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
