export interface Chapter {
  id: string;
  title: string;
  paragraphs: string[];
  autoGenerated: boolean;
}

export interface NovelDocument {
  metadata: {
    title: string;
    formatVersion: 1;
  };
  source: {
    encoding: string;
    autoSegmented: boolean;
  };
  chapters: Chapter[];
}

export function createNovelDocument(
  title: string,
  encoding: string,
  chapters: Chapter[],
): NovelDocument {
  return {
    metadata: { title, formatVersion: 1 },
    source: {
      encoding,
      autoSegmented: chapters.some((chapter) => chapter.autoGenerated),
    },
    chapters,
  };
}

const CHINESE_HEADING = /^\s*第\s*[0-9０-９零〇一二三四五六七八九十百千万两]+\s*[章节卷回部篇](?:\s+|[：:、.．-]?\s*)(\S.*)?\s*$/u;
const ENGLISH_HEADING = /^\s*(?:chapter\s+(?:[0-9]+|[ivxlcdm]+)(?:\s*[:.\-–—]?\s*\S.*)?|prologue(?:\s*[:.\-–—]?\s*\S.*)?|epilogue(?:\s*[:.\-–—]?\s*\S.*)?)\s*$/iu;
const AUTO_SEGMENT_LINES = 200;

function isHeading(line: string): boolean {
  return CHINESE_HEADING.test(line) || ENGLISH_HEADING.test(line);
}

function toParagraphs(lines: string[]): string[] {
  return lines
    .join("\n")
    .trim()
    .split(/\n\s*\n/u)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean);
}

export function parseNovelText(text: string, title: string, encoding: string): NovelDocument {
  const lines = text.replace(/\r\n?|\u2028|\u2029/gu, "\n").split("\n");
  const chapters: Chapter[] = [];
  const preface: string[] = [];
  let heading: string | undefined;
  let body: string[] = [];
  let explicitChapterCount = 0;
  let automaticChapterCount = 0;

  const appendAutomaticSegments = (segmentLines: string[]): void => {
    for (let offset = 0; offset < segmentLines.length; offset += AUTO_SEGMENT_LINES) {
      const paragraphs = toParagraphs(segmentLines.slice(offset, offset + AUTO_SEGMENT_LINES));
      if (paragraphs.length === 0) continue;
      automaticChapterCount += 1;
      chapters.push({
        id: `auto_${String(automaticChapterCount).padStart(4, "0")}`,
        title: `[自动分段 ${automaticChapterCount}]`,
        paragraphs,
        autoGenerated: true,
      });
    }
  };

  const flush = (): void => {
    if (heading === undefined) return;
    explicitChapterCount += 1;
    chapters.push({
      id: `chapter_${String(explicitChapterCount).padStart(4, "0")}`,
      title: heading,
      paragraphs: toParagraphs(body),
      autoGenerated: false,
    });
  };

  for (const line of lines) {
    if (isHeading(line)) {
      if (heading === undefined) appendAutomaticSegments(preface);
      flush();
      heading = line.trim();
      body = [];
    } else if (heading !== undefined) {
      body.push(line);
    } else {
      preface.push(line);
    }
  }
  flush();

  if (heading === undefined) appendAutomaticSegments(preface);

  return createNovelDocument(title, encoding, chapters);
}
